version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: postgrator
      POSTGRES_USER: postgrator
      POSTGRES_DB: postgrator
    ports: 
      - "5432:5432"
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: postgrator
      MYSQL_DATABASE: postgrator
      MYSQL_USER: postgrator
      MYSQL_PASSWORD: postgrator
    ports:
      - "3306:3306"
  # SQL Server needs 2.00 GB of RAM
  sqlserver:
    image: microsoft/mssql-server-linux:latest
    environment:
      ACCEPT_EULA: Y 
      SA_PASSWORD: Postgrator123!
      MSSQL_PID: Express
    ports:
      - "1433:1433"